#!/bin/bash
mkdir /home/abdelrahman/myDirectory
mkdir /home/abdelrahman/myDirectory/secondDirectory
touch /home/abdelrahman/myDirectory/secondDirectory/myNotePaper
cp /home/abdelrahman/myDirectory/secondDirectory/myNotePaper /home/abdelrahman/myDirectory/myNotePaper
mv /home/abdelrahman/myDirectory/myNotePaper /home/abdelrahman/myDirectory/myOldNotePaper
